### ISSUE TITLE
Should change "sage bls12.sage initial_x ..." to "sage bls12.sage initial ..."？

### ISSUE THREAD

**Issue by 3for** [kobigurk/curve_generator#1]
I've run it with the latest sage v8.7,  as the `bls12.sage.py` shown below, the subcommand should be `initial` instead of `initial_x`？
![image](https://user-images.githubusercontent.com/30716372/59896501-789b9200-941b-11e9-912c-197e1a78b968.png)

**Comment by kobigurk** [comment]
You're completely right, thanks!
